# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_naire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('intValue', models.IntegerField(default=0)),
                ('strValue', models.TextField(default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_naire.UserDefine')),
            ],
        ),
    ]
