# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_naire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('intValue', models.IntegerField(default=0)),
                ('strValue', models.TextField(default=b'')),
                ('QContent', models.TextField(default=b'')),
                ('QType', models.TextField(default=b'')),
                ('dim', models.CharField(default=b'', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_naire.UserDefine')),
            ],
        ),
        migrations.AddField(
            model_name='anscount',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_naire.Statics'),
        ),
    ]
