# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_naire', '0002_auto_20160212_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='anscount',
            name='key',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
