# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_naire', '0004_remove_collect_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='username',
            field=models.CharField(default=b'', max_length=16),
        ),
    ]
