# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_naire', '0005_collect_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefine',
            name='headImgSrc',
            field=models.CharField(default=b'https://cdn.jinshuju.net/assets/columbus/avatar_default-5e358f2433179a760ee1ed1f7524eb66.png', max_length=100),
        ),
    ]
